#!/data/data/com.termux/files/usr/bin/sh
# Script untuk memasukkan external repo
#
# install beberapa tools pendukung
apt-get install -y gnupg coreutils apt-transport-https wget

# buat folder source.list baru
mkdir -p /data/data/com.termux/files/usr/etc/apt/sources.list.d

# masukkan external repo
echo "deb [trusted=yes] https://kuburan.github.io/external/ termux extras" > /data/data/com.termux/files/usr/etc/apt/sources.list.d/kuburan.list

# Download signing key
wget https://kuburan.github.io/my.gpg
apt-key add my.gpg

# update
apt-get update

echo
echo "selesai boss !!!"
